Python/Django/Django/Cinema/cinema/cinema/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.contrib.auth.views import login,logout_then_login
from trabajador.views import index
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$',login_required(index), name='index'),
    url(r'^trabajador/',include('trabajador.urls',namespace='trabajador')),
    url(r'^pelicula/',include('pelicula.urls',namespace='pelicula')),
    url(r'^usuario/',include('users.urls',namespace='users')),
    url(r'^accounts/login/',login,{'template_name':'users/login.html'},name='login'),
    url(r'^logout/',logout_then_login, name='logout'),
]

Python/Django/Django/Cinema/cinema/pelicula/urls.py
from django.conf.urls import url
from .views import CrearCategoriaPeliculaView,ListarCategoriaPeliculaView,EliminarCategoriaPeliculaView,EditarCategoriaPeliculaView,CrearRestricciones,ListarRestricciones,EditarRestricciones,EliminarRestricciones,CrearPelicula,ListarPelicula,EditarPelicula,EliminarPelicula
from django.contrib.auth.decorators import login_required

urlpatterns = [
     url(r'^crear_categoria',login_required(CrearCategoriaPeliculaView.as_view()),name='crear_categoria'),
     url(r'^listar_categoria',login_required(ListarCategoriaPeliculaView.as_view()),name='listar_categoria'),
     url(r'^editar_categoria/(?P<pk>\d+)/$',login_required(EditarCategoriaPeliculaView.as_view()),name='editar_categoria'),
     url(r'^eliminar_categoria/(?P<pk>\d+)/$',login_required(EliminarCategoriaPeliculaView.as_view()),name='eliminar_categoria'),


      url(r'^crear_restricciones',login_required(CrearRestricciones.as_view()),name='crear_restricciones'),
      url(r'^listar_restricciones',login_required(ListarRestricciones.as_view()),name='listar_restricciones'),
      url(r'^editar_restricciones/(?P<pk>\d+)/$',login_required(EditarRestricciones.as_view()),name='editar_restricciones'),
      url(r'^eliminar_restricciones/(?P<pk>\d+)/$',login_required(EliminarRestricciones.as_view()),name='eliminar_restricciones'),

      url(r'^crear_pelicula',login_required(CrearPelicula.as_view()),name='crear_pelicula'),
      url(r'^listar_peliculas',login_required(ListarPelicula.as_view()),name='listar_peliculas'),
      url(r'^editar_pelicula/(?P<pk>\d+)/$',login_required(EditarPelicula.as_view()),name='editar_pelicula'),
      url(r'^eliminar_pelicula/(?P<pk>\d+)/$',login_required(EliminarPelicula.as_view()),name='eliminar_pelicula'),
]

Python/Django/Django/Cinema/cinema/users/urls.py
from django.conf.urls import url
from views import RegistroUsuario

urlpatterns = [
    url(r'^registrar',RegistroUsuario.as_view(),name='registrar')
]

Python/Django/Django/Cinema/cinema/pelicula/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

class CategoriaPelicula(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=60)

    def __unicode__(self):
        return self.nombre

class RestriccionesPelicula(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=40)
    observaciones = models.TextField()

    def __unicode__(self):
        return self.nombre

class Pelicula(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length = 255)
    nombre_alterno = models.CharField(max_length = 255)
    duracion = models.CharField( max_length = 50)
    director = models.CharField( max_length = 255)
    elenco = models.TextField()
    grupo_produccion = models.TextField()
    fecha_estreno = models.DateField()
    idioma = models.CharField(max_length = 50)
    pais = models.CharField(max_length = 50)
    distribuidora = models.CharField(max_length = 70)
    descripcion = models.TextField()
    restricciones_pelicula = models.ForeignKey(RestriccionesPelicula, on_delete =models.CASCADE)
    categoria_pelicula = models.ManyToManyField(CategoriaPelicula)

    def __unicode__(self):
        return self.nombre

    class Meta:
        ordering = ['fecha_estreno']

Python/Django/Django/Cinema/cinema/pelicula/forms.py
from django import forms
from .models import CategoriaPelicula,RestriccionesPelicula,Pelicula

class CategoriaPeliculaForm(forms.ModelForm):
    class Meta:
        model = CategoriaPelicula

        fields = [
            'nombre',
        ]

        labels = {
            'nombre':'Nombre de Categoria de Pelicula'
        }

        widgets = {
            'nombre':forms.TextInput()
        }

class RestriccionesPeliculaForm(forms.ModelForm):
    class Meta:
        model = RestriccionesPelicula

        fields = [
            'nombre',
            'observaciones',
        ]

        labels = {
            'nombre':'Nombre',
            'observaciones':'Observaciones',
        }

        widgets = {
            'nombre':forms.TextInput(),
            'observaciones':forms.TextInput(),
        }

class PeliculaForm(forms.ModelForm):
    class Meta:
        model = Pelicula

        fields = [
            'nombre',
            'nombre_alterno',
            'duracion',
            'director',
            'elenco',
            'grupo_produccion',
            'fecha_estreno',
            'idioma',
            'pais',
            'distribuidora',
            'descripcion',
            'restricciones_pelicula',
            'categoria_pelicula',
        ]

        labels = {
            'nombre':'Nombre',
            'nombre_alterno':'Nombre Alterno',
            'duracion':'Duracion',
            'director':'Director',
            'elenco':'Elenco',
            'grupo_produccion':'Produccion',
            'fecha_estreno':'Fecha de Estreno',
            'idioma':'Idioma',
            'pais':'Pais origen',
            'distribuidora':'Distribuidora',
            'descripcion':'Descripcion',
            'restricciones_pelicula':'Restricciones',
            'categoria_pelicula':'Categorias',
        }

        widgets = {
            'nombre': forms.TextInput(),
            'nombre_alterno': forms.TextInput(),
            'duracion': forms.TextInput(),
            'director': forms.TextInput(),
            'elenco': forms.TextInput(),
            'grupo_produccion': forms.TextInput(),
            'fecha_estreno': forms.TextInput(attrs={'placeholder':'AAAA-MM-DD'}),
            'idioma': forms.TextInput(),
            'pais': forms.TextInput(),
            'distribuidora': forms.TextInput(),
            'descripcion': forms.TextInput(),
            'restricciones_pelicula': forms.TextInput(),
            'categoria_pelicula': forms.TextInput(),
        }

Python/Django/Django/Cinema/cinema/pelicula/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic import CreateView,ListView,UpdateView,DeleteView
from django.shortcuts import render
from .models import CategoriaPelicula,RestriccionesPelicula,Pelicula
from .forms import CategoriaPeliculaForm,PeliculaForm,RestriccionesPeliculaForm
from django.core.urlresolvers import reverse_lazy


class CrearCategoriaPeliculaView(CreateView):
    model = CategoriaPelicula
    form_class = CategoriaPeliculaForm
    template_name = 'pelicula/categoria/crear_categoria.html'
    success_url = reverse_lazy('pelicula:listar_categoria')

class ListarCategoriaPeliculaView(ListView):
    model = CategoriaPelicula
    template_name = 'pelicula/categoria/listar_categoria.html'

class EditarCategoriaPeliculaView(UpdateView):
    model = CategoriaPelicula
    form_class = CategoriaPeliculaForm
    template_name = 'pelicula/categoria/actualizar_categoria.html'
    success_url = reverse_lazy('pelicula:listar_categoria')

class EliminarCategoriaPeliculaView(DeleteView):
    model = CategoriaPelicula
    form_class = CategoriaPeliculaForm
    template_name = 'pelicula/categoria/eliminar_categoria.html'
    success_url = reverse_lazy('pelicula:listar_categoria')




class CrearRestricciones(CreateView):
    model = RestriccionesPelicula
    form_class = RestriccionesPeliculaForm
    template_name = 'pelicula/restriccion/crear_restricciones.html'
    success_url = reverse_lazy('pelicula:listar_restricciones')

class ListarRestricciones(ListView):
    model = RestriccionesPelicula
    template_name = 'pelicula/restriccion/listar_restricciones.html'

class EditarRestricciones(UpdateView):
    model = RestriccionesPelicula
    form_class = RestriccionesPeliculaForm
    template_name = 'pelicula/restriccion/actualizar_restricciones.html'
    success_url = reverse_lazy('pelicula:listar_restricciones')

class EliminarRestricciones(DeleteView):
    model = RestriccionesPelicula
    form_class = RestriccionesPeliculaForm
    template_name = 'pelicula/restriccion/eliminar_restricciones.html'
    success_url = reverse_lazy('pelicula:listar_restricciones')


class CrearPelicula(CreateView):
    model = Pelicula
    form_class = PeliculaForm
    template_name = 'pelicula/crear_pelicula.html'
    success_url = reverse_lazy('pelicula/listar_peliculas')

class ListarPelicula(ListView):
    model = Pelicula
    template_name = 'pelicula/listar_peliculas.html'

class EditarPelicula(UpdateView):
    model = Pelicula
    form_class = PeliculaForm
    template_name = 'pelicula/actualizar_pelicula.html'
    success_url = reverse_lazy('pelicula:listar_peliculas')

class EliminarPelicula(DeleteView):
    model = Pelicula
    form_class = PeliculaForm
    template_name = 'pelicula/eliminar_pelicula.html'
    success_url = reverse_lazy('pelicula:listar_peliculas')

Python/Django/Django/Cinema/cinema/pelicula/templates/pelicula/restriccion/actualizar_restricciones.html
{% extends 'cinema/base.html' %}
{% block admin %}../../admin/ {% endblock %}
{% block body %}
<form method="post" class="w3-container">
	{% csrf_token %}
  {{ form.as_p }}
	<div>
		<button type="submit" class="w3-btn w3-round w3-border w3-black">Actualizar</button>
	</div>
  <br>
</form>
{% endblock %}

Python/Django/Django/Cinema/cinema/pelicula/templates/pelicula/restriccion/crear_restricciones.html
{% extends 'cinema/base.html' %}
{% block admin %}../../admin/ {% endblock %}
{% block body %}
<form method="post" class="w3-container">
	{% csrf_token %}
  {{ form.as_p }}
	<div>
		<button type="submit" class="w3-btn w3-round w3-border w3-black">Crear</button>
	</div>
  <br>
</form>
{% endblock %}

Python/Django/Django/Cinema/cinema/pelicula/templates/pelicula/restriccion/eliminar_restricciones.html
{% extends 'cinema/base.html' %}
{% block admin %}../../admin/ {% endblock %}
{% block body %}
<div class="w3-container">
  <form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar la restriccion {{ object.nombre }}?</h3>
    <button class="w3-button w3-border w3-green " name="button">Si,eliminar</button>
    <a href="{% url 'pelicula:listar_restricciones' %} " class="w3-button w3-border w3-green">Cancelar</a>
  </form>
</div>

{% endblock %}

Python/Django/Django/Cinema/cinema/pelicula/templates/pelicula/restriccion/listar_restricciones.html
{% extends 'cinema/base.html' %}
{% block admin %}../../admin/ {% endblock %}

{% block body %}

  <table border="2">
      <thead>
        <tr>
          <td>#</td>
          <td>Nombre</td>
          <td>Observaciones</td>
        </tr>
      </thead>
      <tbody>
        {% if object_list %}
        {% for restricciones in object_list %}
        <tr>
          <td>{{ restricciones.id }}</td>
          <td>{{ restricciones.nombre }}</td>
          <td>
            <a href="{% url 'pelicula:editar_restricciones' restricciones.id %}" class="w3-btn w3-hover-green w3-margin-left"><span class="icon-pencil"></span></a>
            <a href="{% url 'pelicula:eliminar_restricciones' restricciones.id %}" class="w3-btn  w3-hover-green w3-margin-left"><span class="icon-bin"></span></a>
          </td>
        </tr>
        {% endfor %}
        {% else %}
          <h2>No hay registros</h2>
        {% endif %}
      </tbody>
  </table>
{% endblock %}