Python/Django/Django/evento/control_evento/urls.py
from django.conf.urls import url
from .views import ReportePersonasPDF,CrearEvento,ListarEvento,EditarEvento,EliminarEvento,CrearAsistente,EditarAsistente,ListarAsistente,EliminarAsistente,CrearSeminario,ListarSeminario,EliminarSeminario,EditarSeminario
from usuarios.views import home
from django.contrib.auth.decorators import login_required

urlpatterns =  [
	url(r'^$',login_required(home),name = "index"),
	url(r'^reporte_personas_pdf/$',login_required(ReportePersonasPDF.as_view()), name="reporte_personas_pdf"),

	url(r'^crear_asistente/',login_required(CrearAsistente.as_view()),name = "crear_asistente"),
	url(r'^listar_asistente/',login_required(ListarAsistente.as_view()),name = "listar_asistente"),
	url(r'^editar_asistente/(?P<pk>\d+)/$',login_required(EditarAsistente.as_view()),name = "editar_asistente"),
	url(r'^eliminar_asistente/(?P<pk>\d+)/$',login_required(EliminarAsistente.as_view()),name = "eliminar_asistente"),

	url(r'^crear_seminario/',login_required(CrearSeminario.as_view()),name = "crear_seminario"),
	url(r'^listar_seminario/',login_required(ListarSeminario.as_view()),name = "listar_seminario"),
	url(r'^editar_seminario/(?P<pk>\d+)/$',login_required(EditarSeminario.as_view()),name = "editar_seminario"),
	url(r'^eliminar_seminario/(?P<pk>\d+)/$',login_required(EliminarSeminario.as_view()),name = "eliminar_seminario"),
	
	url(r'^crear_evento/',login_required(CrearEvento.as_view()),name = "crear_evento"),
	url(r'^listar_evento/',login_required(ListarEvento.as_view()),name = "listar_evento"),
	url(r'^editar_evento/(?P<pk>\d+)/$',login_required(EditarEvento.as_view()),name = "editar_evento"),
	url(r'^eliminar_evento/(?P<pk>\d+)/$',login_required(EliminarEvento.as_view()),name = "eliminar_evento"),
]

Python/Django/Django/evento/evento/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import login,logout_then_login
from usuarios.views import home
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',login_required(home),name = "index"),
    url(r'^usuarios/', include('usuarios.urls',namespace = "usuarios")),  
    url(r'^ponente/', include('staff.urls',namespace = "ponente")), 
    url(r'^evento/', include('control_evento.urls',namespace = "evento")),    
    url(r'^accounts/login', login,{'template_name':'usuarios/login.html'},name='login'),
    url(r'^logout/',logout_then_login,name='logout'),
    
]

Python/Django/Django/evento/staff/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import CrearPonente,ListarPonente,EditarPonente,EliminarPonente
from usuarios.views import home

urlpatterns =  [
	url(r'^$',login_required(home),name = "index"),
	url(r'^crear_ponente/',login_required(CrearPonente.as_view()),name = "crear_ponente"),
	url(r'^listar_ponente/',login_required(ListarPonente.as_view()),name = "listar_ponente"),
	url(r'^editar_ponente/(?P<pk>\d+)/$',login_required(EditarPonente.as_view()),name = "editar_ponente"),
	url(r'^eliminar_ponente/(?P<pk>\d+)/$',login_required(EliminarPonente.as_view()),name = "eliminar_ponente"),
]

Python/Django/Django/evento/usuarios/urls.py
from django.conf.urls import url
from .views import home, UserCreate
from django.contrib.auth.decorators import login_required

urlpatterns =  [
	url(r'^$',login_required(home),name = "index"),
	url(r'^nuevo_usuario/',UserCreate.as_view(),name = "crear_usuario"),
]

Python/Django/Django/evento/usuarios/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class UserManager(BaseUserManager, models.Manager):

	def _create_user(self, username, email, password, is_staff,
			is_superuser, **extra_fields):
		email = self.normalize_email(email)
		if not email:
			raise ValueError('El email debe ser obligatorio')
		user = self.model(username=username, email=email, is_active=True,
				is_staff=is_staff, is_superuser=is_superuser, **extra_fields)
		user.set_password(password)
		user.save(using = self._db)
		return user

	def create_user(self, username, email, password=None, **extra_fields):
		return self._create_user(username, email, password, False,
			False,**extra_fields)

	def create_superuser(self, username, email, password, **extra_fields):
		return self._create_user(username, email, password, True,
			True, **extra_fields)

class User(AbstractBaseUser,PermissionsMixin):
    username = models.CharField(max_length=30,unique=True)
    email = models.EmailField(max_length=255,unique=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    avatar = models.URLField(blank = True)
    is_regular = models.BooleanField(default = True)
    is_panelista = models.BooleanField(default = False)
    objects = UserManager()
    
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def get_short_name(self):
        return self.username

Python/Django/Django/evento/usuarios/forms.py
from django import forms 
from .models import User
from django.contrib.auth.forms import UserCreationForm

class UserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username','email','first_name','last_name','is_panelista',]
		labels = {'username':'Nombre de usuario','email':'Correo','first_name':'Nombres',
					'last_name':'Apellidos','is_panelista':'Panelista',}
		widgets = {'username':forms.TextInput(),'email':forms.TextInput(),'first_name':forms.TextInput(),
				'last_name':forms.TextInput(),'is_panelista':forms.CheckboxInput(),}

Python/Django/Django/evento/usuarios/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .forms import UserForm
from django.shortcuts import render
from .models import User
from django.views.generic import CreateView
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.forms import UserCreationForm

class UserCreate(CreateView):
	model = User	
	form_class = UserForm
	template_name = 'usuarios/crear_usuario.html'
	success_url = reverse_lazy('index')

def home(request):
	return render(request,'usuarios/base.html')

Python/Django/Django/evento/usuarios/templates/usuarios/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}Asistencia de Evento {% endblock %}</title>
	<link rel="stylesheet" href="{% static 'css/w3.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<div class="w3-bar w3-light-grey">
	  <a href="{% url 'evento:listar_evento' %}" class="w3-bar-item "><button class="w3-button w3-round w3-green">Home</button></a>
	  <a href="{% url 'evento:listar_evento' %}" class="w3-bar-item "><button class="w3-button w3-round w3-green">Evento</button></a>
	  <a href="{% url 'evento:listar_seminario' %}" class="w3-bar-item "> <button class="w3-button w3-round w3-green">Seminario</button></a>
	  <a href="{% url 'evento:crear_asistente' %}" class="w3-bar-item "><button class="w3-button w3-round w3-green">Asistentes</button></a>	  
	</div>

	



</head>
<body>
	{% block body %}
	{% endblock %}
</body>
</html>

Python/Django/Django/evento/usuarios/templates/usuarios/crear_usuario.html
{% extends 'usuarios/base.html' %}

{% block body %}

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <div>
    <button type="submit" name="button">Crear</button>
  </div>
</form>

{% endblock %}

Python/Django/Django/evento/usuarios/templates/usuarios/login.html
{% load staticfiles %}
<html>
	<title>LOGIN</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{% static 'css/w3.css' %}">
	<link rel="stylesheet" href="{% static 'css/fonts/style.css' %}">
	<body>
	
		<div class="w3-container w3-light-grey">
	    <br>
	    <br>
		  <div >
		    <div class="w3-modal-content w3-card-4 w3-teal " style="max-width:600px">
		      <div class="w3-center"><br>	        
		        <img src="{% static 'imagenes/login.jpg' %}" alt="Avatar" style="width:30%" class="w3-circle w3-margin-top">
		      </div>
	
		      <form class="w3-container" method="post">
		      	{% csrf_token %}
		        <div class="w3-section">
		          <label><b>Username</b></label>
		          <input class="w3-input w3-border w3-margin-bottom" type="text" placeholder="Enter Username" name="username" required>
		          <label><b>Password</b></label>
		          <input class="w3-input w3-border" type="password" placeholder="Enter Password" name="password" required>
		          <button class="w3-button w3-block w3-orange w3-section w3-padding" type="submit">Login</button>
		          <a href="{% url 'usuarios:crear_usuario' %}">Registrar</a>
							
		        </div>
		      </form>
	
		      <div class="w3-container w3-border-top w3-padding-16 w3-light-grey">
		        <button onclick="document.getElementById('id01').style.display='none'" type="button" class="w3-button w3-red">Cancel</button>		        
		      </div>
	
		    </div>
		  </div>
		</div>
	
	</body>
	</html>