Python/Django/Django/test1/sala/urls.py
from django.conf.urls import url
from .views import CrearPelicula,ListarPelicula,EditarPelicula,EliminarPelicula,CrearSala,EditarSala,ListarSala,EliminarSala

urlpatterns = [
######PELICULA##############
    url(r'^crear_pelicula/',CrearPelicula.as_view(),name = "crear_pelicula"),
    url(r'^listar_pelicula/',ListarPelicula.as_view(),name = "listar_pelicula"),
    url(r'^editar_pelicula/(?P<pk>\d+)/',EditarPelicula.as_view(),name = "editar_pelicula"),
    url(r'^eliminar_pelicula/(?P<pk>\d+)/',EliminarPelicula.as_view(),name = "eliminar_pelicula"),

##########SALA##############
    url(r'^crear_sala',CrearSala.as_view(),name = "crear_sala"),
    url(r'^listar_sala',ListarSala.as_view(),name = "listar_sala"),
    url(r'^editar_sala/(?P<pk>\d+)/$',EditarSala.as_view(),name = "editar_sala"),
    url(r'^eliminar_sala/(?P<pk>\d+)/$',EliminarSala.as_view(),name = "eliminar_sala"),
]

Python/Django/Django/test1/test1/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import login,logout_then_login
from usuarios.views import index
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',login_required(index), name='index'),
    url(r'^usuarios/',include('usuarios.urls',namespace = "usuarios")),
    url(r'^sala/',include('sala.urls',namespace = "sala")),
    url(r'^compras/',include('compras.urls',namespace = "compras")),
    url(r'^accounts/login', login,{'template_name':'usuarios/login.html'},name='login'),
    url(r'^logout/',logout_then_login,name='logout'),
]

Python/Django/Django/test1/sala/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

class Fila(models.Model):
    fila = models.CharField(unique = True,max_length = 1)


class Butaca(models.Model):
    id = models.AutoField(primary_key = True)
    fila = models.ManyToManyField(Fila)
    numero = models.CharField(max_length = 10)

    def __unicode__(self):
        return self.fila

class Categoria(models.Model):
    id = models.AutoField(primary_key = True)
    categoria = models.CharField(max_length = 255)

    def __unicode__(self):
        return self.categoria

class Pelicula(models.Model):
    id = models.AutoField(primary_key = True)
    nombre = models.CharField(max_length = 255)
    nombre_alterno = models.CharField(max_length = 255, blank = True)
    duracion = models.CharField(max_length = 40)
    categoria = models.ManyToManyField(Categoria)
    fecha_estreno = models.DateField()
    idioma_original = models.CharField(max_length = 255)
    director = models.CharField(max_length = 255)
    sinopsis = models.TextField()

    def __unicode__(self):
        return '%s , %s'%(self.nombre,self.director)

class Sala(models.Model):
    id = models.AutoField(primary_key = True)
    numero = models.CharField(max_length = 2)
    tipo_sala = models.CharField(max_length = 2)
    pelicula = models.ManyToManyField(Pelicula)
    butacas = models.ManyToManyField(Butaca,blank = True)
    cantidad_butacas = models.IntegerField()

    def __unicode__(self):
        return self.numero

Python/Django/Django/test1/sala/forms.py
from django import forms
from .models import Sala,Pelicula


class PeliculaForm(forms.ModelForm):
    class Meta:
        model = Pelicula
        fields = ['nombre','nombre_alterno','duracion','categoria','fecha_estreno','idioma_original',
                    'director','sinopsis',]
        labels = {'nombre':'Nombre','nombre_alterno':'Nombre Alterno','duracion':'Duracion','categoria':'Categoria','fecha_estreno':'Fecha de Estreno',
        'idioma_original':'Idioma de Origen','director':'Director','sinopsis':'Sinopsis',}

        widgets = {'nombre':forms.TextInput(),'nombre_alterno':forms.TextInput(),'duracion':forms.TextInput(),'categoria':forms.CheckboxSelectMultiple(),'fecha_estreno':forms.TextInput(),
        'idioma_original':forms.TextInput(),'director':forms.TextInput(),'sinopsis':forms.Textarea(),}
class SalaForm(forms.ModelForm):
    class Meta:
        model = Sala
        fields = ['numero','tipo_sala','pelicula','butacas','cantidad_butacas',]
        labels = {'numero':'Numero de Sala','tipo_sala':'Tipo de sala','pelicula':'Pelicula','butacas':'Butacas','cantidad_butacas':'Numero de butacas'}
        widgets = {'numero':forms.TextInput(),'tipo_sala':forms.TextInput(),'pelicula':forms.CheckboxSelectMultiple(),'butacas':forms.CheckboxSelectMultiple(),'cantidad_butacas':forms.TextInput(),}

Python/Django/Django/test1/sala/views.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render
from django.views.generic import CreateView,DeleteView,UpdateView,ListView
from .models import Pelicula,Sala
from .forms import PeliculaForm,SalaForm

#####################################################
#PELICULA

class CrearPelicula(CreateView):
    model = Pelicula
    form_class = PeliculaForm
    template_name = 'pelicula/crear_pelicula.html'
    success_url = reverse_lazy('sala:listar_pelicula')

class ListarPelicula(ListView):
    model = Pelicula
    template_name = 'pelicula/listar_pelicula.html'

class EditarPelicula(UpdateView):
    model = Pelicula
    form_class = PeliculaForm
    template_name = 'pelicula/editar_pelicula.html'
    success_url = reverse_lazy('sala:listar_pelicula')

class EliminarPelicula(DeleteView):
    model = Pelicula
    form_class = PeliculaForm
    template_name = 'pelicula/eliminar_pelicula.html'
    success_url = reverse_lazy('sala:listar_pelicula')


#######################################################
#SALA

class CrearSala(CreateView):
    model = Sala
    form_class = SalaForm
    template_name = 'sala/crear_sala.html'
    success_url = reverse_lazy('sala:listar_sala')


class ListarSala(ListView):
    model = Sala
    template_name = 'sala/listar_sala.html'

class EditarSala(UpdateView):
    model = Sala
    form_class = SalaForm
    template_name = 'sala/editar_sala.html'
    success_url = reverse_lazy('sala:listar_sala')


class EliminarSala(DeleteView):
    model = Sala
    form_class = SalaForm
    template_name = 'sala/eliminar_sala.html'
    success_url = reverse_lazy('sala:listar_sala')

Python/Django/Django/test1/sala/templates/pelicula/crear_pelicula.html
{% extends 'test1/base.html' %}

{% block body %}

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <div>
    <button type="submit" name="button">Crear</button>
  </div>
</form>

{% endblock %}

Python/Django/Django/test1/sala/templates/pelicula/editar_pelicula.html
{% extends 'test1/base.html' %}
{% block body %}

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <div>
    <button type="submit" name="button">Actualizar</button>
  </div>
</form>

{% endblock %}

Python/Django/Django/test1/sala/templates/pelicula/eliminar_pelicula.html
{% extends 'test1/base.html' %}
{% block body %}

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <div>
    <button type="submit" name="button">Eliminar</button>
    <a class="btn" href="{% url 'sala:listar_pelicula' %}">Cancelar</a>
  </div>
</form>

{% endblock %}

Python/Django/Django/test1/sala/templates/pelicula/listar_pelicula.html
{% extends 'test1/base.html' %}


{% block body %}
<table border="2">
  {% if object_list %}
    <thead>
      <tr>
        <td>#</td>
        <td>Nombre</td>
        <td>Nombre Alterno</td>
        <td>Duracion</td>
        <td>Categoria</td>
        <td>Fecha de Estreno</td>
        <td>Idioma Original</td>
        <td>Director</td>
        <td>Sinopsis</td>
        <td>Accion</td>
      </tr>
    </thead>
    <tbody>
      {% for pelicula in object_list %}
      <tr>
        <td>{{ pelicula.id }}</td>
        <td>{{ pelicula.nombre }}</td>
        <td>{{ pelicula.nombre_alterno }}</td>
        <td>{{ pelicula.duracion }}</td>
        <td>
          <ul>{% for categoria in pelicula.categoria.all %}
    				<li>
    					{{categoria.categoria}}
    				</li>
    				{% endfor %}
    			</ul>
        </td>
        <td>{{ pelicula.fecha_estreno }}</td>
        <td>{{ pelicula.idioma_original }}</td>
        <td>{{ pelicula.director }}</td>
        <td>{{ pelicula.sinopsis }}</td>
        <td>
          <a href="{% url 'sala:editar_pelicula' pelicula.id %}">Editar</a>
          <a href="{% url 'sala:eliminar_pelicula' pelicula.id %}">Eliminar</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  {% else %}
    <h2>No se existen datos que mostrar</h2>
  {% endif %}
</table>

{% endblock %}