Python/Django/Django/evento/evento/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.views import login,logout_then_login
from usuarios.views import home
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',login_required(home),name = "index"),
    url(r'^usuarios/', include('usuarios.urls',namespace = "usuarios")),  
    url(r'^ponente/', include('staff.urls',namespace = "ponente")), 
    url(r'^evento/', include('control_evento.urls',namespace = "evento")),    
    url(r'^accounts/login', login,{'template_name':'usuarios/login.html'},name='login'),
    url(r'^logout/',logout_then_login,name='logout'),
    
]

Python/Django/Django/evento/staff/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import CrearPonente,ListarPonente,EditarPonente,EliminarPonente
from usuarios.views import home

urlpatterns =  [
	url(r'^$',login_required(home),name = "index"),
	url(r'^crear_ponente/',login_required(CrearPonente.as_view()),name = "crear_ponente"),
	url(r'^listar_ponente/',login_required(ListarPonente.as_view()),name = "listar_ponente"),
	url(r'^editar_ponente/(?P<pk>\d+)/$',login_required(EditarPonente.as_view()),name = "editar_ponente"),
	url(r'^eliminar_ponente/(?P<pk>\d+)/$',login_required(EliminarPonente.as_view()),name = "eliminar_ponente"),
]

Python/Django/Django/evento/staff/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Ponente(models.Model):
	id = models.AutoField(primary_key = True)
	nombre = models.CharField(max_length = 255)
	apellidos = models.CharField(max_length = 255)
	dni = models.CharField(max_length = 10)
	email = models.EmailField()
	grados = models.TextField()
	titulos = models.TextField()
	lugares_trabajo = models.TextField()

	def __unicode__(self):
		return '%s , %s'%(self.nombre,self.apellidos)

Python/Django/Django/evento/staff/forms.py
from django import forms
from .models import Ponente

class PonenteForm(forms.ModelForm):
	class Meta:
		model = Ponente
		fields = ['nombre','apellidos','dni','email','grados','titulos','lugares_trabajo',]
		widgets = {'nombre':forms.TextInput(),'apellidos':forms.TextInput(),'dni':forms.TextInput(),'email':forms.TextInput(),
					'grados':forms.Textarea(),'titulos':forms.Textarea(),'lugares_trabajo':forms.Textarea(),}

sadas
dasdas

Python/Django/Django/evento/staff/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import Ponente
from django.shortcuts import render
from .forms import PonenteForm

from django.views.generic import CreateView,DeleteView,UpdateView,ListView
from django.core.urlresolvers import reverse_lazy

class CrearPonente(CreateView):
    model = Ponente 
    form_class = PonenteForm
    template_name = 'ponente/crear_ponente.html'
    success_url = reverse_lazy('ponente:listar_ponente')

class ListarPonente(ListView):
    model = Ponente 
    template_name = 'ponente/listar_ponente.html'

class EditarPonente(UpdateView):
    model = Ponente
    form_class = PonenteForm 
    template_name = 'ponente/editar_ponente.html'
    success_url = reverse_lazy('ponente:listar_ponente')

class EliminarPonente(DeleteView):
    model = Ponente
    form_class = PonenteForm
    template_name = 'ponente/eliminar_ponente.html'
    success_url = reverse_lazy('ponente:listar_ponente')

Python/Django/Django/evento/staff/templates/ponente/crear_ponente.html
{% extends 'usuarios/base.html' %}

{% block body %}

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <div>
    <button type="submit" name="button">Crear</button>
  </div>
</form>

{% endblock %}

Python/Django/Django/evento/staff/templates/ponente/editar_ponente.html
{% extends 'usuarios/base.html' %}

{% block body %}

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <div>
    <button type="submit" name="button">Editar</button>
  </div>
</form>

{% endblock %}

Python/Django/Django/evento/staff/templates/ponente/eliminar_ponente.html
{% extends 'usuarios/base.html' %}

{% block body %}

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <div>
    <button type="submit" name="button">Eliminar</button>
    <a href="{% url 'index' %}">Cancelar</a>
  </div>
</form>

{% endblock %}

Python/Django/Django/evento/staff/templates/ponente/listar_ponente.html
{% extends 'usuarios/base.html' %}

{% block body %}
<table border="3">
	<thead>
		<tr>
			<td>#</td>
			<td>Nombre</td>
			<td>Apellido</td>
			<td>Dni</td>
			<td>Email</td>
			<td>Grados</td>
			<td>Titulos</td>
			<td>Lugares de trabajo</td>
			<td>Accion</td>
		</tr>
	</thead>
	<tbody>
	{% if object_list %}
	{% for ponente in object_list %}
		<tr>
			<td>{{ ponente.id }}</td>
			<td>{{ ponente.nombre }}</td>
			<td>{{ ponente.apellidos }}</td>
			<td>{{ ponente.dni }}</td>
			<td>{{ ponente.email }}</td>
			<td>{{ ponente.grados }}</td>
			<td>{{ ponente.titulos }}</td>
			<td>{{ ponente.lugares_trabajo }}</td>
			<td>
				<a href="{% url 'ponente:editar_ponente' ponente.id %}">Editar</a>
				<a href="{% url 'ponente:eliminar_ponente' ponente.id %}">Eliminar</a>
			</td>
		</tr>
		{% endfor %}
	 {% else %}
	 	<h1>No hay elementos que mostrar</h1>
	 {% endif %}
	</tbody>
</table>

{% endblock %}